### ISSUE TITLE
TODO Feature Selection

### ISSUE THREAD

**Issue by VicenteAR** [FragileTech/feature_selection#6]
- [ ] Allow option to choose number of iterations
- [ ] Easier way to choose only one iteration 
- [ ] Return a list of features whose size corresponds to target_features
- [ ] Better algorithm to choose the number of features removed each loop 

_Optional_ 
- [ ] The module computes which is the best target_features size to maximise model performance
